# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KU0Ta-AmVXKemsKP0pakc6qY6_E26Tl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style='whitegrid', palette='Set2')
print('✅ Bibliothèques chargées avec succès')

df = pd.read_csv('Global_Cybersecurity_Threats_2015-2024.csv')
print(f'✅ Dataset chargé : {df.shape[0]} lignes, {df.shape[1]} colonnes')

print('🔍 5 premières lignes :')
df.head()

print('🔍 5 dernières lignes :')
df.tail()

print(f'📊 Nombre de lignes   : {df.shape[0]}')

print(f'📊 Nombre de colonnes : {df.shape[1]}')

print(f'\n📋 Colonnes :')
for col in df.columns:
    print(f'   → {col}')

print('🔎 Types des colonnes :')
print(df.dtypes)

print('⏱️ Colonne temporelle : Year')
print('⚠️  Données annuelles uniquement')

df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
print(f'\n📅 Années disponibles : {sorted(df["Year"].unique())}')

fig, ax = plt.subplots(figsize=(10, 4))
df['Year'].value_counts().sort_index().plot(
    kind='bar', ax=ax, color='steelblue')
ax.set_title('Distribution des incidents par année')
ax.set_xlabel('Année')
ax.set_ylabel('Nombre d\'incidents')
plt.tight_layout()
plt.show()

print('❓ Valeurs manquantes par colonne :')
print(df.isnull().sum())

print('\n📊 Pourcentage :')
print((df.isnull().sum() / len(df) * 100).round(2))

print('✅ Aucune valeur manquante détectée.')
print('📌 Aucune action nécessaire.')

nb_doublons = df.duplicated().sum()
print(f'🔁 Lignes dupliquées : {nb_doublons}')

df = df.drop_duplicates()
print(f'✅ Après suppression : {len(df)} lignes')



print(f'🔎 Doublons restants : {df.duplicated().sum()}')

num_cols = [
    'Financial Loss (in Million $)',
    'Number of Affected Users',
    'Incident Resolution Time (in Hours)'
]

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for i, col in enumerate(num_cols):
    axes[i].boxplot(df[col].dropna(), patch_artist=True,
                    boxprops=dict(facecolor='lightblue'))
    axes[i].set_title(f'Boxplot : {col}')
    axes[i].set_ylabel(col)

plt.suptitle('Détection des outliers', fontsize=13)
plt.tight_layout()
plt.show()

print('📊 Statistiques descriptives :')
df[num_cols].describe()

plt.figure(figsize=(7, 5))
corr = df[num_cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            linewidths=0.5, square=True)
plt.title('Matrice de corrélation')
plt.tight_layout()
plt.show()

# Q26/Q27/Q28/Q29 — Distribution des 6 attaques
attack_counts = df['Attack Type'].value_counts()
attack_pct    = (attack_counts / len(df) * 100).round(2)

print('📊 Distribution des types d\'attaques :')
for att, cnt in attack_counts.items():
    print(f'  {att:25s} : {cnt} ({attack_pct[att]}%)')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

attack_counts.plot(kind='bar', ax=axes[0],
                   color=sns.color_palette('Set2', 6))
axes[0].set_title('Nombre d\'incidents par attaque')
axes[0].set_xlabel('Type d\'attaque')
axes[0].set_ylabel('Nombre')
axes[0].tick_params(axis='x', rotation=30)

axes[1].pie(attack_counts,
            labels=attack_counts.index,
            autopct='%1.1f%%',
            colors=sns.color_palette('Set2', 6),
            startangle=140)
axes[1].set_title('Répartition des attaques')

plt.suptitle('Variable cible : Attack Type', fontsize=13)
plt.tight_layout()
plt.show()

print(f'\n📌 Dataset équilibré ? ✅ Oui (~16-17% par classe)')

df.to_csv('clean_network_dataset.csv', index=False)
print('✅ Sauvegardé : clean_network_dataset.csv')
print(f'📊 Dimensions finales : {df.shape}')


from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import collections

# Encodage des variables catégorielles
df_encoded = df.copy()

cat_cols = [
    'Country',
    'Target Industry',
    'Attack Source',
    'Security Vulnerability Type',
    'Defense Mechanism Used'
]

encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    encoders[col] = le

# Encodage de la variable cible
le_target = LabelEncoder()
df_encoded['Attack Type'] = le_target.fit_transform(
    df_encoded['Attack Type'])

print('✅ Encodage terminé')
print(f'\n🎯 Classes encodées :')
for i, cls in enumerate(le_target.classes_):
    print(f'   {i} → {cls}')

# Q5 — Séparer X et y
X = df_encoded.drop(columns=['Attack Type'])
y = df_encoded['Attack Type']

print(f'🔹 X (features) : {X.shape}')
print(f'🔹 y (target)   : {y.shape}')
print(f'\n📋 Features utilisées :')
for col in X.columns:
    print(f'   → {col}')

# Q1/Q2/Q3 — Vérification équilibre + SMOTE
print('📊 Distribution avant SMOTE :')
print(y.value_counts())

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

print('\n📊 Distribution après SMOTE :')
counter = collections.Counter(y_res)
for k, v in sorted(counter.items()):
    print(f'   {le_target.classes_[k]:25s}: {v}')

print(f'\n✅ Total après SMOTE : {len(X_res)} lignes')

# Q4/Q6 — Split
X_train, X_temp, y_train, y_temp = train_test_split(
    X_res, y_res,
    test_size=0.30,
    random_state=42,
    stratify=y_res
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

# Q7 — Tailles
print('✅ Split effectué :')
print(f'   🔹 Train      : {X_train.shape[0]} lignes '
      f'({X_train.shape[0]/len(X_res)*100:.1f}%)')
print(f'   🔹 Validation : {X_val.shape[0]} lignes '
      f'({X_val.shape[0]/len(X_res)*100:.1f}%)')
print(f'   🔹 Test       : {X_test.shape[0]} lignes '
      f'({X_test.shape[0]/len(X_res)*100:.1f}%)')

# Q8 — Vérifier distribution conservée
import pandas as pd

print('📊 Distribution des classes :')
for name, y_part in [('Train', y_train),
                      ('Validation', y_val),
                      ('Test', y_test)]:
    counts = collections.Counter(y_part)
    total = len(y_part)
    print(f'\n  {name} :')
    for k in sorted(counts):
        pct = counts[k]/total*100
        print(f'    {le_target.classes_[k]:25s}: '
              f'{counts[k]:4d} ({pct:.1f}%)')

# Q9/Q10 — StandardScaler
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_val_sc   = scaler.transform(X_val)
X_test_sc  = scaler.transform(X_test)

print('✅ StandardScaler appliqué')
print(f'   Train      : {X_train_sc.shape}')
print(f'   Validation : {X_val_sc.shape}')
print(f'   Test       : {X_test_sc.shape}')

# ► Étape 4 : Entraînement des Algorithmes
# ================================================

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np

print('✅ Modèles importés avec succès')

# Q1/Q2/Q3 — Logistic Regression
print('🔵 Entraînement Logistic Regression...')

lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_sc, y_train)

lr_score = lr.score(X_val_sc, y_val)
print(f'✅ Score validation : {lr_score:.4f}')

# Variables les plus importantes
feature_names = X.columns.tolist()
coef_abs = np.abs(lr.coef_).mean(axis=0)
feat_lr = pd.Series(coef_abs, index=feature_names)\
            .sort_values(ascending=False)

print('\n📊 Variables les plus importantes :')
for feat, val in feat_lr.head(5).items():
    print(f'   → {feat:40s}: {val:.4f}')

# Q4/Q5/Q6 — KNN
print('🟡 Test de plusieurs valeurs de K...')

k_values = [3, 5, 7, 9, 11]
knn_scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_sc, y_train)
    score = knn.score(X_val_sc, y_val)
    knn_scores.append(score)
    print(f'   K={k:2d} → score = {score:.4f}')

best_k = k_values[np.argmax(knn_scores)]
print(f'\n✅ Meilleur K = {best_k} '
      f'(score = {max(knn_scores):.4f})')

plt.figure(figsize=(7, 4))
plt.plot(k_values, knn_scores, marker='o', color='orange')
plt.axvline(best_k, color='red', linestyle='--',
            label=f'Meilleur K={best_k}')
plt.title('Impact de K sur les performances KNN')
plt.xlabel('Valeur de K')
plt.ylabel('Score validation')
plt.legend()
plt.tight_layout()
plt.show()

# Meilleur KNN
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train_sc, y_train)
print(f'✅ KNN entraîné avec K={best_k}')

# Q7/Q8/Q9/Q10/Q11 — Random Forest
print('🌲 Entraînement Random Forest...')

rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)
rf.fit(X_train_sc, y_train)

rf_score = rf.score(X_val_sc, y_val)
print(f'✅ Score validation : {rf_score:.4f}')
print(f'📌 Nombre d\'arbres : {rf.n_estimators}')
print(f'📌 Profondeur max  : {rf.max_depth}')

# Feature importance
feat_rf = pd.Series(
    rf.feature_importances_,
    index=feature_names
).sort_values(ascending=False)

plt.figure(figsize=(8, 5))
feat_rf.plot(kind='bar', color='forestgreen')
plt.title('Importance des variables — Random Forest')
plt.ylabel('Importance')
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()

print(f'\n🏆 Variable la plus importante : '
      f'{feat_rf.idxmax()}')

# Q12/Q13 — SVM
print('🔴 Entraînement SVM...')

svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train_sc, y_train)

svm_score = svm.score(X_val_sc, y_val)
print(f'✅ Score validation : {svm_score:.4f}')

# Comparaison des 4 modèles
print('📊 Comparaison des scores (validation) :')
print('-' * 45)

scores_dict = {
    'Logistic Regression' : lr_score,
    f'KNN (K={best_k})'   : max(knn_scores),
    'Random Forest'       : rf_score,
    'SVM'                 : svm_score
}

for model, sc in sorted(scores_dict.items(),
                         key=lambda x: -x[1]):
    bar = '█' * int(sc * 30)
    print(f'  {model:25s}: {sc:.4f} {bar}')

best_name = max(scores_dict, key=scores_dict.get)
print(f'\n🏆 Meilleur modèle : {best_name} '
      f'({scores_dict[best_name]:.4f})')

# ► Étape 5 : Évaluation des Modèles
# ================================================

from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score,
    roc_auc_score, confusion_matrix,
    classification_report, roc_curve
)
from sklearn.preprocessing import label_binarize

print('✅ Métriques importées avec succès')

# Fonction d'évaluation complète
def evaluate_model(name, model, X_t, y_t):
    y_pred = model.predict(X_t)
    y_prob = model.predict_proba(X_t)

    acc  = accuracy_score(y_t, y_pred)
    prec = precision_score(y_t, y_pred,
                           average='weighted',
                           zero_division=0)
    rec  = recall_score(y_t, y_pred,
                        average='weighted',
                        zero_division=0)
    f1   = f1_score(y_t, y_pred,
                    average='weighted',
                    zero_division=0)
    auc  = roc_auc_score(y_t, y_prob,
                         multi_class='ovr',
                         average='weighted')

    return {
        'Modèle'    : name,
        'Accuracy'  : round(acc,  4),
        'Precision' : round(prec, 4),
        'Recall'    : round(rec,  4),
        'F1-score'  : round(f1,   4),
        'ROC-AUC'   : round(auc,  4)
    }

print('✅ Fonction d\'évaluation prête')

# Évaluation des 4 modèles sur jeu de TEST
results = []
results.append(evaluate_model(
    'Logistic Regression', lr, X_test_sc, y_test))
results.append(evaluate_model(
    f'KNN (K={best_k})', knn_best, X_test_sc, y_test))
results.append(evaluate_model(
    'Random Forest', rf, X_test_sc, y_test))
results.append(evaluate_model(
    'SVM', svm, X_test_sc, y_test))

results_df = pd.DataFrame(results).set_index('Modèle')

print('📊 Résultats sur le jeu de TEST :')
print(results_df.to_string())

# Visualisation comparative
metrics = ['Accuracy','Precision','Recall',
           'F1-score','ROC-AUC']
x = np.arange(len(metrics))
width = 0.2
colors = ['steelblue','orange','forestgreen','crimson']

fig, ax = plt.subplots(figsize=(13, 6))
for i, (idx, row) in enumerate(results_df.iterrows()):
    ax.bar(x + i*width,
           [row[m] for m in metrics],
           width, label=idx, color=colors[i])

ax.set_xticks(x + width*1.5)
ax.set_xticklabels(metrics)
ax.set_ylim(0, 1.15)
ax.set_title('Comparaison des modèles — Jeu de test')
ax.set_ylabel('Score')
ax.legend()
ax.axhline(0.9, color='gray', linestyle='--',
           alpha=0.5, label='Seuil 0.9')
plt.tight_layout()
plt.show()

# Meilleur modèle
best_model_name = results_df['F1-score'].idxmax()
model_map = {
    'Logistic Regression' : lr,
    f'KNN (K={best_k})'   : knn_best,
    'Random Forest'       : rf,
    'SVM'                 : svm
}
best_model = model_map[best_model_name]
y_pred_best = best_model.predict(X_test_sc)

# Matrice de confusion
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(9, 7))
sns.heatmap(cm, annot=True, fmt='d',
            cmap='Blues',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_)
plt.title(f'Matrice de confusion — {best_model_name}')
plt.ylabel('Réel')
plt.xlabel('Prédit')
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()

print(f'\n📋 Rapport — {best_model_name} :')
print(classification_report(
    y_test, y_pred_best,
    target_names=le_target.classes_))

# Q9/Q10/Q11 — Courbe ROC
y_test_bin = label_binarize(
    y_test, classes=np.unique(y_test))
y_prob_best = best_model.predict_proba(X_test_sc)

colors_roc = ['blue','orange','green',
              'red','purple','brown']

plt.figure(figsize=(9, 6))
for i, cls in enumerate(le_target.classes_):
    fpr, tpr, _ = roc_curve(
        y_test_bin[:, i], y_prob_best[:, i])
    auc_i = roc_auc_score(
        y_test_bin[:, i], y_prob_best[:, i])
    plt.plot(fpr, tpr,
             color=colors_roc[i],
             label=f'{cls} (AUC={auc_i:.2f})')

plt.plot([0,1],[0,1],'k--', alpha=0.4)
plt.xlabel('Taux de Faux Positifs')
plt.ylabel('Taux de Vrais Positifs')
plt.title(f'Courbes ROC — {best_model_name}')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

print(f'\n🏆 Meilleur modèle : {best_model_name}')
print(f'   ROC-AUC : '
      f'{results_df.loc[best_model_name,"ROC-AUC"]:.4f}')

# ► Étape 6 : SOC AI
# ================================================

print("=" * 55)
print("ÉTAPE 6 : SOC AI — ANALYSE & RECOMMANDATIONS")
print("=" * 55)

# Q1/Q2 — Meilleur algorithme
print('\n🏆 RÉSULTATS FINAUX :')
print(results_df.to_string())

best_name = results_df['F1-score'].idxmax()
best_f1   = results_df.loc[best_name, 'F1-score']
best_auc  = results_df.loc[best_name, 'ROC-AUC']

print(f'\n✅ Meilleur modèle : {best_name}')
print(f'   F1-score : {best_f1:.4f}')
print(f'   ROC-AUC  : {best_auc:.4f}')
from google.colab import files

files.download('best_model.pkl')
files.download('scaler.pkl')
files.download('label_encoder.pkl')

print('✅ Fichiers téléchargés !')